layout_spectrum: 0.3709731970448047
typography_spectrum: 0.6911689073313028
color:
  brandColors:
    - '#000000'
    - '#98E5FE'
    - '#35AEFE'
    - '#827555'
    - '#1573CA'
  brandStrength: 0.8876015851274133
  lightness: 0.3405715418048203
  saturation: 0.5574607527814806
  rhythmicContrast: 0.905308484332636
content_rating:
  adult: false
opengraph:
  type: website
  appId: '249783212081793'
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/d176d8f9-7cb6-4eb0-867e-27e1d17e97b3.jpg
author:
  name: Cole Thomason
  url: ''
  email: Colethomason@gmail.com
name: Cole Thomason Music
navigation:
  - name: follow us on facebook
    url: facebook.com/colethomasoneverybody
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/432da3ff-86be-4360-8264-0537f67124b9.jpg
title: Welcome to the official Cole Thomason website
