layout_spectrum: 0.3760529435239732
typography_spectrum: 0.4194837943650782
color:
  brandColors:
    - '#000000'
    - '#98E5FE'
    - '#35AEFE'
    - '#827555'
    - '#1573CA'
  brandStrength: 0.008506648940965533
  lightness: 0.47791661974042654
  saturation: 0.6344162670429796
  rhythmicContrast: 0.6280338598880917
coverPrefs:
  filter: false
content_rating:
  adult: false
opengraph:
  type: website
  appId: '249783212081793'
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/d176d8f9-7cb6-4eb0-867e-27e1d17e97b3.jpg
author:
  name: Cole Thomason
  url: colethomason.com
  email: Colethomason@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4e0a269c-97b8-45ae-a4f9-3a67c38f706b.png
name: 'Cole Thomason: Songwriter, Singer, Musician'
navigation:
  - name: Like us on facebook
    url: 'http://facebook.com/colethomasoneverybody'
    type: external
  - name: Upcoming Shows
    id: 231091f7-f88e-45bd-b842-f8ab7dc56a5a
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/432da3ff-86be-4360-8264-0537f67124b9.jpg
title: "\_ColeThomason.com"
description: 'Check-in on the latest albums, shows, and stories it''s all right here.'
