layout_spectrum: 1
name: Cole Thomason Music
title: Welcome to the official Cole Thomason website
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.9787234
  lightness: 0.5702128
  saturation: 0.7787234
  rhythmicContrast: 0.8319149
  brandColors:
    - '#210408'
    - '#FCFBE5'
    - '#373632'
    - '#6D3421'
    - '#DED1B5'
typography_spectrum: 0.1085106
