typography_spectrum: 0.1085106
color:
  brandColors:
    - '#210408'
    - '#FCFBE5'
    - '#373632'
    - '#6D3421'
    - '#DED1B5'
  brandStrength: 0.9787234
  lightness: 0.9808511
  saturation: 0.7787234
  rhythmicContrast: 0.2468085
opengraph:
  appId: '249783212081793'
layout_spectrum: 1
author:
  name: Cole Thomason
  email: Colethomason@gmail.com
name: Cole Thomason Music
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/432da3ff-86be-4360-8264-0537f67124b9.jpg
title: Welcome to the official Cole Thomason website
